baseURL = "https://openutm.com"
languageCode = "en-us"
title = "OpenUTM"
theme = "hugo-ink"

copyright = "OpenUTM Limited. All rights reserved."

# Modern configs
[pagination]
  pagerSize = 10

# Explicitly structure disqus as an empty map block
[services]
  [services.disqus]
    shortname = "" 

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Number of characters to show in summary.
summaryLength = 25

[params]
    disqusShortname = ""
    
    # Content types which are included in home page recent posts list.
    mainSections = ["articles"]

    # Content types which are excludes Disqus comments.
    disableDisqusTypes = ["page", "post"]

    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
    featherIconsCDN = true

    # Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
    favicon = "/icons/favicon.ico"

    # Switch to dark mode or auto detect mode from OS (Optional).
    mode = "auto"

# Main menu which appears below site header.
[[menu.main]]
name = "All Articles"
url = "/articles"
weight = 1

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 2

[[menu.main]]
name = "About OpenUTM"
url = "https://openutm.com"
weight = 3

# Social media links which shows up on site header.
[[params.social]]
name = "Home"
icon = "globe"
url = "https://openutm.com"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com"

# Enable tags.
[taxonomies]
   category = "categories"
